import { createFileRoute } from '@tanstack/react-router'
import { ArrowLeft, Database, Globe2, Shield, Users } from 'lucide-react'
import { leagues } from '@/game-data'

export const Route = createFileRoute('/leagues')({
  head: () => ({ meta: [{ title: 'Base de ligas · Futebol Diretor Pro' }, { name: 'description', content: 'Ligas e clubes disponíveis no banco inicial do simulador.' }] }),
  component: LeaguesPage,
})

function LeaguesPage() {
  return <main className="min-h-dvh bg-background px-5 py-8 text-foreground md:px-10"><div className="mx-auto max-w-6xl"><a href="/" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline"><ArrowLeft className="h-4 w-4" />Voltar ao centro de comando</a><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-primary">Banco esportivo</p><h1 className="mt-2 font-serif text-4xl">Seis mercados, um mundo vivo</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Snapshot inicial com clubes das principais divisões e moeda local. O conteúdo está separado por liga para receber atualizações de temporada sem quebrar os saves.</p></div><div className="flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-3 text-xs"><Database className="h-4 w-4 text-primary" />Snapshot 2026 · referência + estimativas</div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{leagues.map((league) => <article key={league.id} className="rounded-xl border border-border bg-card p-5 shadow-sm transition-all hover:-translate-y-1 hover:shadow-md"><div className="flex items-start justify-between"><span className="rounded-lg bg-primary/10 p-2 text-primary"><Globe2 className="h-5 w-5" /></span><span className="font-mono text-xs text-muted-foreground">{league.currency}</span></div><h2 className="mt-5 font-serif text-2xl">{league.name}</h2><p className="mt-1 text-sm text-muted-foreground">{league.country}</p><div className="mt-5 flex items-center gap-4 border-t border-border pt-4 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Shield className="h-3.5 w-3.5 text-primary" />{league.clubs.length} clubes</span><span className="flex items-center gap-1.5"><Users className="h-3.5 w-3.5 text-primary" />mercado ativo</span></div><div className="mt-4 flex flex-wrap gap-1.5">{league.clubs.slice(0, 6).map((club) => <span key={club} className="rounded-md bg-muted px-2 py-1 text-[10px] font-medium">{club}</span>)}<span className="rounded-md bg-accent px-2 py-1 text-[10px] font-bold text-accent-foreground">+{league.clubs.length - 6}</span></div></article>)}</div></div></main>
}
