import { useMemo, useState } from 'react'
import { ArrowLeft, Check, CircleDollarSign, Filter, Newspaper, Search, Shield, Sparkles, Trophy, Users } from 'lucide-react'
import { featuredPlayers, formatMoney, leagues, clubInitials } from '@/game-data'

type Module = 'squad' | 'finance' | 'market' | 'competitions' | 'press'

const moduleCopy: Record<Module, { eyebrow: string; title: string; description: string }> = {
  squad: { eyebrow: 'Clube / elenco & staff', title: 'Elenco sob sua responsabilidade', description: 'Controle contratos, hierarquia, moral e prontidão do grupo antes de cada decisão esportiva.' },
  finance: { eyebrow: 'Clube / finanças', title: 'O caixa conta a história', description: 'Acompanhe entradas, saídas e compromissos para não trocar futuro esportivo por uma crise financeira.' },
  market: { eyebrow: 'Mercado global', title: 'Negociar é construir vantagem', description: 'Encontre oportunidades, compare risco e abra negociações com parcelas e salários realistas.' },
  competitions: { eyebrow: 'Competições', title: 'A temporada em perspectiva', description: 'Veja o calendário, a classificação e os impactos de cada resultado sobre a meta do conselho.' },
  press: { eyebrow: 'Imprensa & mundo', title: 'A narrativa também joga', description: 'Rumores, entrevistas e crises mudam a confiança do vestiário, da torcida e do conselho.' },
}

const financeRows = [
  ['Bilheteria', '+ R$ 410 mil', 'Receita projetada para o próximo jogo', 'positive'],
  ['Patrocínio master', '+ R$ 1,2 mi', 'Parcela mensal · vence em 12 dias', 'positive'],
  ['Folha salarial', '− R$ 6,82 mi', '8,4% acima do orçamento', 'negative'],
  ['Dívida bancária', '− R$ 890 mil', 'Parcela + juros · vence em 19 dias', 'negative'],
]

export function ManagementPage({ module }: { module: Module }) {
  const copy = moduleCopy[module]
  const [query, setQuery] = useState('')
  const [notice, setNotice] = useState<string | null>(null)
  const [selected, setSelected] = useState<string | null>(null)
  const [simulated, setSimulated] = useState(false)
  const filteredPlayers = useMemo(() => featuredPlayers.filter((p) => `${p.name} ${p.club} ${p.position}`.toLowerCase().includes(query.toLowerCase())), [query])

  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(null), 2600) }

  return <main className="min-h-dvh bg-background px-5 py-8 text-foreground md:px-10"><div className="mx-auto max-w-6xl"><a href="/" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline"><ArrowLeft className="h-4 w-4" />Centro de comando</a><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-primary">{copy.eyebrow}</p><h1 className="mt-2 font-serif text-4xl tracking-tight">{copy.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{copy.description}</p></div><button onClick={() => flash('Alterações salvas no caderno do clube.')} className="rounded-lg bg-primary px-4 py-3 text-sm font-bold text-primary-foreground shadow-md transition hover:-translate-y-0.5 hover:shadow-lg">Salvar decisão</button></div>{notice && <div className="mb-5 flex items-center gap-2 rounded-lg border border-primary/30 bg-primary/10 px-4 py-3 text-sm font-semibold text-primary"><Check className="h-4 w-4" />{notice}</div>}{module === 'squad' && <Squad content={filteredPlayers} query={query} setQuery={setQuery} selected={selected} setSelected={setSelected} flash={flash} />}{module === 'finance' && <Finance flash={flash} />}{module === 'market' && <Market flash={flash} />}{module === 'competitions' && <Competitions simulated={simulated} onSimulate={() => setSimulated(true)} />}{module === 'press' && <Press flash={flash} />}</div></main>
}

function Squad({ content, query, setQuery, selected, setSelected, flash }: { content: typeof featuredPlayers; query: string; setQuery: (value: string) => void; selected: string | null; setSelected: (value: string | null) => void; flash: (value: string) => void }) { return <><div className="mb-5 flex flex-col gap-3 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-lg border border-border bg-card px-3 py-2.5"><Search className="h-4 w-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Buscar jogador, clube ou posição" /></label><button onClick={() => flash('Filtro avançado: jogadores com contrato curto')} className="flex items-center justify-center gap-2 rounded-lg border border-border bg-card px-4 py-2.5 text-sm font-bold hover:bg-muted"><Filter className="h-4 w-4" />Filtros</button></div><div className="grid gap-4 md:grid-cols-2">{content.map((player) => <article key={`${player.name}-${player.club}`} className="rounded-xl border border-border bg-card p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start gap-3"><ClubBadge name={player.club} /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h2 className="font-bold">{player.name}</h2><span className="rounded-md bg-primary/10 px-2 py-1 text-xs font-black text-primary">OVR {player.overall}</span></div><p className="mt-1 text-xs text-muted-foreground">{player.position} · {player.age} anos · {player.club}</p></div></div><div className="mt-4 grid grid-cols-3 gap-3 border-t border-border pt-4 text-xs"><div><p className="text-muted-foreground">Valor</p><p className="mt-1 font-bold">{formatMoney(player.value, player.club === 'Palmeiras' || player.club === 'Flamengo' || player.club === 'Fluminense' ? 'BRL' : 'EUR')}</p></div><div><p className="text-muted-foreground">Salário</p><p className="mt-1 font-bold">{formatMoney(player.salary, 'BRL')}</p></div><div><p className="text-muted-foreground">Contrato</p><p className="mt-1 font-bold">{player.contract.slice(0, 5)}</p></div></div><button onClick={() => { setSelected(selected === player.name ? null : player.name); flash(`${player.name}: relatório de scout aberto.`) }} className="mt-4 w-full rounded-lg border border-border px-3 py-2 text-xs font-bold hover:bg-muted">{selected === player.name ? 'Fechar relatório' : 'Abrir relatório de scout'}</button>{selected === player.name && <div className="mt-3 rounded-lg bg-muted p-3 text-xs leading-5 text-muted-foreground">Profissionalismo alto · adaptabilidade boa · pressão psicológica moderada · interesse em mudança: negociável.</div>}</article>)}</div></> }

function Finance({ flash }: { flash: (value: string) => void }) { return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><FinanceStat icon={CircleDollarSign} label="Caixa" value="R$ 18,4 mi" note="+4,2% no mês" /><FinanceStat icon={Users} label="Folha" value="R$ 6,82 mi" note="8,4% acima do limite" /><FinanceStat icon={Shield} label="Dívidas" value="R$ 42,7 mi" note="R$ 890 mil vencendo" /></div><section className="overflow-hidden rounded-xl border border-border bg-card shadow-sm"><div className="border-b border-border px-5 py-4"><h2 className="font-serif text-2xl">Fluxo de caixa projetado</h2></div>{financeRows.map(([name, value, detail, tone]) => <div key={name} className="flex flex-col gap-2 border-b border-border px-5 py-4 last:border-0 sm:flex-row sm:items-center"><div className="flex-1"><p className="text-sm font-bold">{name}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><p className={`font-mono text-sm font-bold ${tone === 'positive' ? 'text-primary' : 'text-destructive'}`}>{value}</p></div>)}</section><button onClick={() => flash('Relatório financeiro exportado para o conselho.')} className="rounded-lg border border-border bg-card px-4 py-3 text-sm font-bold hover:bg-muted">Exportar relatório do conselho</button></div> }
function FinanceStat({ icon: Icon, label, value, note }: { icon: typeof CircleDollarSign; label: string; value: string; note: string }) { return <div className="rounded-xl border border-border bg-card p-5 shadow-sm"><Icon className="h-5 w-5 text-primary" /><p className="mt-5 text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div> }
function Market({ flash }: { flash: (value: string) => void }) { return <div className="grid gap-4 md:grid-cols-2">{featuredPlayers.slice(0, 8).map((player) => <article key={player.name} className="rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><ClubBadge name={player.club} /><div className="flex-1"><h2 className="font-bold">{player.name}</h2><p className="text-xs text-muted-foreground">{player.club} · {player.position} · potencial {player.potential}</p></div><p className="font-bold text-primary">{formatMoney(player.value, 'EUR')}</p></div><div className="mt-4 flex gap-2"><button onClick={() => flash(`Proposta inicial aberta por ${player.name}.`)} className="flex-1 rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground">Abrir negociação</button><button onClick={() => flash('Jogador adicionado à lista de observação.')} className="rounded-lg border border-border px-3 py-2 text-xs font-bold hover:bg-muted"><Sparkles className="h-3.5 w-3.5" /></button></div></article>)}</div> }
function Competitions({ simulated, onSimulate }: { simulated: boolean; onSimulate: () => void }) { return <div className="space-y-5"><section className="rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Brasileirão · rodada 21</p><h2 className="mt-2 font-serif text-3xl">Aurora FC <span className="text-muted-foreground">×</span> Náutico Central</h2><p className="mt-2 text-sm text-muted-foreground">Domingo, 09 ago · 16:00 · Estádio Municipal</p></div><button onClick={onSimulate} className="flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-3 text-sm font-bold text-primary-foreground"><Trophy className="h-4 w-4" />{simulated ? 'Jogo simulado' : 'Simular rapidamente'}</button></div>{simulated && <div className="mt-5 grid grid-cols-3 items-center rounded-lg bg-muted p-5 text-center"><div><p className="text-xs text-muted-foreground">Aurora FC</p><p className="mt-2 text-4xl font-black">2</p></div><div><p className="font-mono text-xs text-muted-foreground">FINAL</p><p className="mt-2 text-xs text-primary">xG 1,74 × 0,92</p></div><div><p className="text-xs text-muted-foreground">Náutico</p><p className="mt-2 text-4xl font-black">1</p></div></div>}</section><div className="grid gap-4 md:grid-cols-2"><Table title="Classificação" rows={['1  Palmeiras · 44 pts', '2  Flamengo · 42 pts', '3  Aurora FC · 36 pts', '4  Botafogo · 35 pts']} /><Table title="Calendário próximo" rows={['09 ago · Náutico Central · casa', '13 ago · Bahia · fora', '17 ago · Copa do Brasil · casa', '24 ago · Palmeiras · fora']} /></div></div> }
function Table({ title, rows }: { title: string; rows: string[] }) { return <section className="rounded-xl border border-border bg-card p-5 shadow-sm"><h2 className="font-serif text-xl">{title}</h2><div className="mt-4 space-y-3">{rows.map((row) => <p key={row} className="border-b border-border pb-3 text-sm last:border-0">{row}</p>)}</div></section> }
function Press({ flash }: { flash: (value: string) => void }) { const stories = ['Conselho avalia investimento recorde na base do Aurora', 'Empresário de Matheus Lima vaza interesse do Braga', 'Torcida prepara mosaico para jogo decisivo de domingo']; return <div className="space-y-4">{stories.map((story, index) => <article key={story} className="rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex gap-4"><div className="rounded-lg bg-primary/10 p-3 text-primary"><Newspaper className="h-5 w-5" /></div><div className="flex-1"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{index === 0 ? 'Clube' : index === 1 ? 'Mercado' : 'Torcida'} · há {index + 2}h</p><h2 className="mt-2 font-serif text-xl">{story}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">A repercussão pode alterar confiança, pressão e ambiente do clube. Escolha uma postura pública antes do próximo boletim.</p><button onClick={() => flash('Resposta pública registrada: tom institucional e transparente.')} className="mt-4 rounded-lg border border-border px-3 py-2 text-xs font-bold hover:bg-muted">Responder à imprensa</button></div></div></article>)}</div> }
function ClubBadge({ name }: { name: string }) { return <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-primary/25 bg-primary/10 text-xs font-black text-primary" title={`${name} · escudo textual do dataset`}>{clubInitials(name)}</div> }
