import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Check, CircleDollarSign, Newspaper, Search, Shield, Sparkles, Trophy, Users, UserRoundPlus, X } from 'lucide-react'
import { featuredPlayers, formatMoney, clubInitials, type Player } from '@/game-data'
import { createInitialState, formatSalary, loadState, saveState, type ClubState, type StaffMember } from '@/game-state'

type Module = 'squad' | 'finance' | 'market' | 'competitions' | 'press'
const moduleCopy: Record<Module, { eyebrow: string; title: string; description: string }> = {
  squad: { eyebrow: 'Clube / elenco & staff', title: 'Elenco sob sua responsabilidade', description: 'Gerencie jogadores, staff, contratos e o plano de jogo do Aurora.' },
  finance: { eyebrow: 'Clube / finanças', title: 'O caixa conta a história', description: 'Acompanhe entradas, saídas e decisões que protegem o futuro do clube.' },
  market: { eyebrow: 'Mercado global', title: 'Negociar é construir vantagem', description: 'Faça propostas, contrate jogadores e acompanhe sua lista de observação.' },
  competitions: { eyebrow: 'Competições', title: 'A temporada em perspectiva', description: 'Simule partidas, acompanhe a tabela e ajuste a estratégia do conselho.' },
  press: { eyebrow: 'Imprensa & mundo', title: 'A narrativa também joga', description: 'Responda a histórias e mantenha a confiança de torcida e conselho.' },
}
const financeRows = [['Bilheteria', '+ R$ 410 mil', 'Receita projetada para o próximo jogo', true], ['Patrocínio master', '+ R$ 1,2 mi', 'Parcela mensal · vence em 12 dias', true], ['Folha salarial', '− R$ 6,82 mi', '8,4% acima do orçamento', false], ['Dívida bancária', '− R$ 890 mil', 'Parcela + juros · vence em 19 dias', false]] as const

export function ManagementPage({ module }: { module: Module }) {
  const copy = moduleCopy[module]
  const [state, setState] = useState<ClubState>(createInitialState)
  const [query, setQuery] = useState('')
  const [notice, setNotice] = useState<string | null>(null)
  const [selected, setSelected] = useState<string | null>(null)
  const [hydrated, setHydrated] = useState(false)
  useEffect(() => { setState(loadState()); setHydrated(true) }, [])
  useEffect(() => { if (hydrated) saveState(state) }, [hydrated, state])
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(null), 2600) }
  const filtered = useMemo(() => featuredPlayers.filter((p) => `${p.name} ${p.club} ${p.position}`.toLowerCase().includes(query.toLowerCase())), [query])
  const signPlayer = (player: Player) => {
    if (state.squad.some((item) => item.name === player.name)) return flash(`${player.name} já está no seu elenco.`)
    if (state.transferBudget < player.value) return flash('Orçamento insuficiente. Venda atletas ou peça reforço ao conselho.')
    setState((current) => ({ ...current, transferBudget: current.transferBudget - player.value, squad: [...current.squad, { ...player, club: 'Aurora FC' }], signed: [...current.signed, player.name] }))
    flash(`${player.name} contratado para o Aurora FC.`)
  }
  const toggleWatch = (name: string) => setState((current) => ({ ...current, watched: current.watched.includes(name) ? current.watched.filter((item) => item !== name) : [...current.watched, name] }))
  return <main className="min-h-dvh bg-background px-5 py-8 text-foreground md:px-10"><div className="mx-auto max-w-6xl"><a href="/" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline"><ArrowLeft className="h-4 w-4" />Centro de comando</a><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-primary">{copy.eyebrow}</p><h1 className="mt-2 font-serif text-4xl tracking-tight">{copy.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{copy.description}</p></div><div className="flex items-center gap-2"><span className="rounded-lg border border-border bg-card px-3 py-2 text-xs font-bold">Caixa {formatMoney(state.balance, 'BRL')}</span><button onClick={() => flash('Decisões salvas no save local.')} className="rounded-lg bg-primary px-4 py-3 text-sm font-bold text-primary-foreground shadow-md hover:-translate-y-0.5 hover:shadow-lg">Salvar decisão</button></div></div>{notice && <div className="mb-5 flex items-center justify-between gap-2 rounded-lg border border-primary/30 bg-primary/10 px-4 py-3 text-sm font-semibold text-primary"><span className="flex items-center gap-2"><Check className="h-4 w-4" />{notice}</span><button onClick={() => setNotice(null)} aria-label="Fechar aviso"><X className="h-4 w-4" /></button></div>}{module === 'squad' && <Squad squad={state.squad} staff={state.staff} content={filtered} query={query} setQuery={setQuery} selected={selected} setSelected={setSelected} />}{module === 'finance' && <Finance flash={flash} />}{module === 'market' && <Market content={filtered} watched={state.watched} onWatch={toggleWatch} onSign={signPlayer} flash={flash} />}{module === 'competitions' && <Competitions />}{module === 'press' && <Press flash={flash} />}</div></main>
}

function Squad({ squad, staff, content, query, setQuery, selected, setSelected }: { squad: Player[]; staff: StaffMember[]; content: Player[]; query: string; setQuery: (value: string) => void; selected: string | null; setSelected: (value: string | null) => void }) { const [tab, setTab] = useState<'players' | 'staff'>('players'); const visibleSquad = squad.filter((player) => `${player.name} ${player.club} ${player.position}`.toLowerCase().includes(query.toLowerCase())); return <><div className="mb-5 flex flex-wrap gap-2"><button onClick={() => setTab('players')} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === 'players' ? 'bg-primary text-primary-foreground' : 'border border-border bg-card'}`}>Jogadores ({squad.length})</button><button onClick={() => setTab('staff')} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === 'staff' ? 'bg-primary text-primary-foreground' : 'border border-border bg-card'}`}>Staff ({staff.length})</button>{tab === 'players' && <label className="ml-auto flex min-w-[240px] flex-1 items-center gap-2 rounded-lg border border-border bg-card px-3 py-2"><Search className="h-4 w-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Buscar jogador" /></label>}</div>{tab === 'players' ? <div className="grid gap-4 md:grid-cols-2">{visibleSquad.map((player) => <PlayerCard key={`${player.name}-${player.club}`} player={player} selected={selected} setSelected={setSelected} action="elenco" />)}</div> : <div className="grid gap-4 md:grid-cols-2">{staff.map((member) => <StaffCard key={member.name} member={member} />)}</div>}<p className="mt-6 text-xs text-muted-foreground">Use a aba Mercado para contratar jogadores. As contratações são salvas automaticamente neste navegador.</p>{tab === 'players' && visibleSquad.length === 0 && <p className="p-8 text-center text-sm text-muted-foreground">Nenhum atleta encontrado.</p>}</> }
function PlayerCard({ player, selected, setSelected, action }: { player: Player; selected: string | null; setSelected: (value: string | null) => void; action: string }) { return <article className="rounded-xl border border-border bg-card p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start gap-3"><ClubBadge name={player.club} /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h2 className="font-bold">{player.name}</h2><span className="rounded-md bg-primary/10 px-2 py-1 text-xs font-black text-primary">OVR {player.overall}</span></div><p className="mt-1 text-xs text-muted-foreground">{player.position} · {player.age} anos · {player.club}</p></div></div><div className="mt-4 grid grid-cols-3 gap-3 border-t border-border pt-4 text-xs"><div><p className="text-muted-foreground">Valor</p><p className="mt-1 font-bold">{formatMoney(player.value, 'EUR')}</p></div><div><p className="text-muted-foreground">Salário</p><p className="mt-1 font-bold">{formatSalary(player.salary)}</p></div><div><p className="text-muted-foreground">Contrato</p><p className="mt-1 font-bold">{player.contract.slice(0, 5)}</p></div></div><button onClick={() => setSelected(selected === player.name ? null : player.name)} className="mt-4 w-full rounded-lg border border-border px-3 py-2 text-xs font-bold hover:bg-muted">{selected === player.name ? 'Fechar relatório' : `Abrir relatório de ${action}`}</button>{selected === player.name && <div className="mt-3 rounded-lg bg-muted p-3 text-xs leading-5 text-muted-foreground">Profissionalismo alto · adaptabilidade boa · potencial {player.potential} · interesse em mudança negociável.</div>}</article> }
function StaffCard({ member }: { member: StaffMember }) { return <article className="rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-full bg-secondary p-3 text-secondary-foreground"><UserRoundPlus className="h-5 w-5" /></div><div><h2 className="font-bold">{member.name}</h2><p className="text-xs text-muted-foreground">{member.role}</p></div><span className="ml-auto text-lg font-black text-primary">{member.rating}</span></div><div className="mt-4 flex justify-between border-t border-border pt-3 text-xs"><span className="text-muted-foreground">Salário mensal</span><span className="font-bold">{formatSalary(member.salary)}</span></div></article> }
function Finance({ flash }: { flash: (value: string) => void }) { return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><FinanceStat icon={CircleDollarSign} label="Caixa" value="R$ 18,4 mi" note="+4,2% no mês" /><FinanceStat icon={Users} label="Folha" value="R$ 6,82 mi" note="8,4% acima do limite" /><FinanceStat icon={Shield} label="Dívidas" value="R$ 42,7 mi" note="R$ 890 mil vencendo" /></div><section className="overflow-hidden rounded-xl border border-border bg-card shadow-sm">{financeRows.map(([name, value, detail, positive]) => <div key={name} className="flex flex-col gap-2 border-b border-border px-5 py-4 last:border-0 sm:flex-row sm:items-center"><div className="flex-1"><p className="text-sm font-bold">{name}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><p className={`font-mono text-sm font-bold ${positive ? 'text-primary' : 'text-destructive'}`}>{value}</p></div>)}</section><button onClick={() => flash('Relatório financeiro exportado para o conselho.')} className="rounded-lg border border-border bg-card px-4 py-3 text-sm font-bold hover:bg-muted">Exportar relatório do conselho</button></div> }
function FinanceStat({ icon: Icon, label, value, note }: { icon: typeof CircleDollarSign; label: string; value: string; note: string }) { return <div className="rounded-xl border border-border bg-card p-5 shadow-sm"><Icon className="h-5 w-5 text-primary" /><p className="mt-5 text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div> }
function Market({ content, watched, onWatch, onSign, flash }: { content: Player[]; watched: string[]; onWatch: (name: string) => void; onSign: (player: Player) => void; flash: (message: string) => void }) { return <div className="space-y-4"><div className="flex items-center gap-2 rounded-lg border border-primary/20 bg-primary/5 p-4 text-sm"><Trophy className="h-4 w-4 text-primary" />Orçamento de transferências: <strong>R$ 7,2 mi</strong>. Clique em contratar para concluir a operação.</div><div className="grid gap-4 md:grid-cols-2">{content.slice(0, 12).map((player) => <article key={player.name} className="rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><ClubBadge name={player.club} /><div className="flex-1"><h2 className="font-bold">{player.name}</h2><p className="text-xs text-muted-foreground">{player.club} · {player.position} · potencial {player.potential}</p></div><p className="font-bold text-primary">{formatMoney(player.value, 'EUR')}</p></div><div className="mt-4 flex gap-2"><button onClick={() => onSign(player)} className="flex-1 rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground">Contratar jogador</button><button onClick={() => { onWatch(player.name); flash(watched.includes(player.name) ? 'Removido da observação.' : 'Adicionado à observação.') }} className={`rounded-lg border px-3 py-2 text-xs font-bold ${watched.includes(player.name) ? 'border-accent bg-accent/30' : 'border-border hover:bg-muted'}`}><Sparkles className="h-3.5 w-3.5" /></button></div></article>)}</div></div> }
function Competitions() { return <div className="grid gap-4 md:grid-cols-2"><Table title="Classificação" rows={['1  Palmeiras · 44 pts', '2  Flamengo · 42 pts', '3  Aurora FC · 36 pts', '4  Botafogo · 35 pts']} /><Table title="Calendário próximo" rows={['09 ago · Náutico Central · casa', '13 ago · Bahia · fora', '17 ago · Copa do Brasil · casa', '24 ago · Palmeiras · fora']} /><a href="/simulation" className="rounded-xl border border-primary/30 bg-primary/5 p-5 font-bold text-primary hover:bg-primary/10">Abrir Match Center e assistir à simulação lance a lance →</a></div> }
function Table({ title, rows }: { title: string; rows: string[] }) { return <section className="rounded-xl border border-border bg-card p-5 shadow-sm"><h2 className="font-serif text-xl">{title}</h2><div className="mt-4 space-y-3">{rows.map((row) => <p key={row} className="border-b border-border pb-3 text-sm last:border-0">{row}</p>)}</div></section> }
function Press({ flash }: { flash: (value: string) => void }) { const stories = ['Conselho avalia investimento recorde na base do Aurora', 'Empresário de Matheus Lima vaza interesse do Braga', 'Torcida prepara mosaico para jogo decisivo de domingo']; return <div className="space-y-4">{stories.map((story, index) => <article key={story} className="rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex gap-4"><div className="rounded-lg bg-primary/10 p-3 text-primary"><Newspaper className="h-5 w-5" /></div><div className="flex-1"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{index === 0 ? 'Clube' : index === 1 ? 'Mercado' : 'Torcida'} · há {index + 2}h</p><h2 className="mt-2 font-serif text-xl">{story}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">A repercussão pode alterar confiança, pressão e ambiente do clube.</p><button onClick={() => flash('Resposta pública registrada e reputação atualizada.')} className="mt-4 rounded-lg border border-border px-3 py-2 text-xs font-bold hover:bg-muted">Responder à imprensa</button></div></div></article>)}</div> }
function ClubBadge({ name }: { name: string }) { return <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-primary/25 bg-primary/10 text-xs font-black text-primary" title={`${name} · escudo textual`}>{clubInitials(name)}</div> }
